"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query";

const queryClient = new QueryClient();
const inter = Inter({ subsets: ["latin"] });
// Não pode ser exportado do lado do cliente.
// Talvez seja melhor usar react-query só na rota do chat.
/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <html className="h-full" lang="en">
        <body className={inter.className + " h-full"}>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
